Add file dropzone functionality for SVG drag and drop
yoksel/url-encoder pull request #64
Opened 2023-02-14 10:04 UTC by thomas-franz

Hey there! 👋🏼 
Thanks for creating and maintaining @yoksel  :)
Been using this tool for many years now and finally wanted to contribute something to it.

This feature allows you to simply drag and drop SVGs into the tool.

Let me know if theres anything I should adjust/change.

2023-02-23 20:52 UTC, yoksel requested changes

2023-02-23 20:52 UTC, yoksel commented on src/scss/styles.scss
> +#dropzone {
Use classes for stylization, please. They allows to use modifiers like in other classes here. 
With modifier selectors will look like `.dropzone` and `.dropzone--active`

2023-02-23 20:54 UTC, yoksel commented
Cool, very convenient!
Tiny comment to code

2023-08-15 09:50 UTC, thomas-franz commented
Hey @yoksel , did the changes and it should be ready now.
Please let me know if there's anything else to change.

2023-08-15 18:01 UTC, merged

2023-08-15 18:03 UTC, yoksel commented
Thank you!